### ISSUE TITLE
browserify hangs after install with npm3

### ISSUE THREAD

**Issue by sendlo** [paypal/generator-react-engine#7]
Using npm 3 my npm install failed because it didn't automatically load all the peer dependencies.  But the generator went on to run browserify anyway, even after the failed install.  Then browserify stalled without any messaging because it couldn't find a dependency.

It took a lot of digging to find the issue.  I don't think most people would give it a second chance.  Is there  a way to catch when peer dependencies aren't installed?  Alternatively, is there a way to catch when browserify fails, rather than letting it hang?  Maybe update grunt-browserify.

**Comment by vuhwang** [comment]
@sendlo Although I did not see the particular error you described, I was able to see the error below which should now be fixed with generator-react-enigne@1.0.2.  Please let me know if you continue to see an issue.  Thanks.

```npm start

> exp@0.1.0 start /Users/vhwang/Views/test/generator-react-engine-test/exp
> npm run browserify && node index.js


> exp@0.1.0 browserify /Users/vhwang/Views/test/generator-react-engine-test/exp
> browserify -t reactify -t require-globify public/index.js -o public/bundle.js

Error: Cannot find module 'history' from '/Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/react-engine/lib'
    at /Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:46:17
    at process (/Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:92:31)
    at /Users/vhwang/Views/test/generator-react-engine-test/exp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
{```

**Comment by vuhwang** [comment]
@sendlo closing this issue.  please open a new issue if you continue to have problems.

**Comment by sendlo** [comment]
Thanks. That did it. Two other peer dependencies are not installed, but those aren't causing browserify to stall.
